---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-vellun-io-v1beta1-gpugroup
  failurePolicy: Fail
  name: mgpugroup-v1beta1.kb.io
  rules:
  - apiGroups:
    - vellun.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gpugroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-vellun-io-v1beta1-gpunetworkpolicy
  failurePolicy: Fail
  name: mgpunetworkpolicy-v1beta1.kb.io
  rules:
  - apiGroups:
    - vellun.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gpunetworkpolicies
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-vellun-io-v1beta1-gpugroup
  failurePolicy: Fail
  name: vgpugroup-v1beta1.kb.io
  rules:
  - apiGroups:
    - vellun.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gpugroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-vellun-io-v1beta1-gpunetworkpolicy
  failurePolicy: Fail
  name: vgpunetworkpolicy-v1beta1.kb.io
  rules:
  - apiGroups:
    - vellun.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gpunetworkpolicies
  sideEffects: None
