# This rule is not used by the project vellun itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over vellun.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vellun
    app.kubernetes.io/managed-by: kustomize
  name: gpugroup-admin-role
rules:
- apiGroups:
  - vellun.io
  resources:
  - gpugroups
  verbs:
  - '*'
- apiGroups:
  - vellun.io
  resources:
  - gpugroups/status
  verbs:
  - get
